# src/secrets_loader/secrets_loader.pyi

class SecretsLoader:
    _instance: "SecretsLoader" | None
    _loaded_env: dict[str, str | None]
    _used_keys: set[str]
    _filepath: str | None

    def __new__(cls, filepath: str | None = ...) -> "SecretsLoader": ...
    @classmethod
    def _load_initial_env(cls, filepath: str | None) -> None: ...
    def get(self, key: str, default: str | None = ...) -> str | None: ...
    @property
    def filepath(self) -> str | None: ...
    @property
    def used_keys(self) -> set[str]: ...
    def __setattr__(self, name: str, value: str) -> None: ...
    def __delattr__(self, name: str) -> None: ...
